#!/usr/bin/env python3
"""Rebuild docs/EVIDENCE.md from register/entries/*.json and validate every entry (Article 5.1, Rule 3.4).

Entries cite the clauses they rest on in `adopted_in` as "Article N.M" (CONSTITUTION.md) or "Rule N.M" (GOVERNANCE.md).
"""
import json, glob, os, re, sys, collections
try: import jsonschema
except ImportError: jsonschema=None
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
schema=json.load(open(os.path.join(root,'register/schema.json')))
files=sorted(glob.glob(os.path.join(root,'register/entries/*.json')))
E=[]
for f in files:
    e=json.load(open(f))
    if jsonschema: jsonschema.validate(e,schema)
    if e['id']!=os.path.basename(f)[:-5]: sys.exit(f"id/file mismatch: {f}")
    E.append(e)

def headings(path, prefix):
    out=[]
    for line in open(os.path.join(root,path), encoding='utf-8'):
        m=re.match(rf"^#{{2,3}} {prefix} (\d+)\. (.+)$", line.strip())
        if m: out.append((int(m.group(1)), m.group(2).strip()))
        if line.startswith("## Preamble"): out.append((0,"Preamble"))
    return out

ART=headings('CONSTITUTION.md','Article')   # [(n,title)]
RUL=headings('GOVERNANCE.md','Rule')
art_titles={n:t for n,t in ART}; rul_titles={n:t for n,t in RUL}
by_art=collections.defaultdict(list); by_rule=collections.defaultdict(list); bad=[]
for e in E:
    for a in e.get('adopted_in',[]):
        m=re.match(r"^(Article|Rule) (\d+)(?:\.(\d+))?$", a)
        if not m: bad.append((e['id'],a)); continue
        n=int(m.group(2))
        if m.group(1)=="Article":
            if n not in art_titles: bad.append((e['id'],a)); continue
            by_art[n].append((a,e))
        else:
            if n not in rul_titles: bad.append((e['id'],a)); continue
            by_rule[n].append((a,e))
if bad: sys.exit(f"adopted_in references that do not exist: {bad}")

v=lambda k: sum(e['assessment']['verdict']==k for e in E)
def cell(items): return '<br>'.join(f"{a}: [{e['provision']}](../register/entries/{e['id']}.json) ({e['assessment']['verdict']})" for a,e in sorted(items,key=lambda x:(x[0],x[1]['id'])))
out=[f"""# Evidence map

Which register entries each article of the [constitution](../CONSTITUTION.md) and each rule of the [operating rules](../GOVERNANCE.md) rest on (Article 5.1, Rule 3.4). An article with no entry is marked untested. Entries carry the clause in their `adopted_in` field; this file is generated by `scripts/build_evidence.py`, do not edit by hand. Verdicts: worked = copy, mixed = copy with the stated correction, critical = the clause exists to avoid this.

Register: {len(E)} entries, all status "proposed" unless stated (Rule 3.3: assessments are contested in the open). By verdict: worked {v('worked')}, mixed {v('mixed')}, critical {v('critical')}.

Endurance findings (Elkins, Ginsburg, Melton, *The Endurance of National Constitutions*, 2009): of 935 national constitutions since 1789, half lived less than nineteen years. Three design choices raise survival: inclusion in drafting and amendment, a usable amendment procedure, and specificity. Articles 10, 18, 19 and 20 follow the first two. On specificity the finding cuts against a short text; that is recorded here as an open question.

## Constitution

| Article | Rests on | Status |
|---|---|---|"""]
untested=[]
for n,t in ART:
    label = "Preamble" if n==0 else f"{n} {t}"
    if by_art[n]: out.append(f"| {label} | {cell(by_art[n])} | {len(by_art[n])} entries |")
    else: out.append(f"| {label} | | untested |"); untested.append(label)
out.append("""
## Operating rules

| Rule | Rests on | Status |
|---|---|---|""")
for n,t in RUL:
    if by_rule[n]: out.append(f"| {n} {t} | {cell(by_rule[n])} | {len(by_rule[n])} entries |")
    else: out.append(f"| {n} {t} | | untested |"); untested.append(f"Rule {n} {t}")
out.append(f"""
## Untested

{'; '.join(untested) if untested else 'none'}. Article 8 (knowledge, truth and machines) says of itself that it has not been tried at the scale of a constitution. Rule 2 (agents) rests partly on non-state precedents documented in docs/LANDSCAPE.md (Wikipedia agent policy, 1f916 quotas) that are not yet register entries. Adding them is open work.

## Register index

| Entry | Source | Verdict | Lesson |
|---|---|---|---|""")
for e in E:
    out.append(f"| [{e['provision']}](../register/entries/{e['id']}.json) | {e['source']['constitution']}, {e['source']['year']} | {e['assessment']['verdict']} | {e['lesson']} |")
open(os.path.join(root,'docs/EVIDENCE.md'),'w').write('\n'.join(out)+'\n')
print(f"{len(E)} entries valid; evidence map written; untested: {untested}")
