#!/usr/bin/env python3
"""Rebuild docs/EVIDENCE.md from register/entries/*.json and validate every entry (Article 7.4)."""
import json, glob, os, sys
try: import jsonschema
except ImportError: jsonschema=None
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
schema=json.load(open(os.path.join(root,'register/schema.json')))
files=sorted(glob.glob(os.path.join(root,'register/entries/*.json')))
E=[]
for f in files:
    e=json.load(open(f))
    if jsonschema: jsonschema.validate(e,schema)
    E.append(e)
titles=['Preamble','1 Purpose','2 Members','3 Principles','4 Layers','5 Decisions','6 Agents','7 Work','8 Money','9 Stewardship and transfer','10 Amendment and versions','11 Ratification and sunset','12 Forking and licence']
by={t:[] for t in titles}
for e in E:
    for a in e.get('adopted_in',[]):
        n=a.replace('Article ','').split('.')[0]
        for t in titles:
            if t.split(' ')[0]==n: by[t].append((a,e))
v=lambda k: sum(e['assessment']['verdict']==k for e in E)
out=[f"""# Evidence map

Which register entries each article of the constitution rests on (Articles 3.2 and 7.4). An article with no entry is marked untested. Entries carry the article in their `adopted_in` field; this file is generated by `scripts/build_evidence.py`, do not edit by hand. Verdicts: worked = copy, mixed = copy with the stated correction, critical = the article exists to avoid this.

Register: {len(E)} entries, all status "proposed" unless stated (Article 7.3: assessments are contested in the open). By verdict: worked {v('worked')}, mixed {v('mixed')}, critical {v('critical')}.

Endurance findings (Elkins, Ginsburg, Melton, *The Endurance of National Constitutions*, 2009): of 935 national constitutions since 1789, half lived less than nineteen years. Three design choices raise survival: inclusion in drafting and amendment, a usable amendment procedure, and specificity. Articles 4, 5, 10 and 11 follow the first two. On specificity the finding cuts against a short text; that is recorded here as an open question.

| Article | Rests on | Status |
|---|---|---|"""]
for t in titles:
    if by[t]:
        cells='<br>'.join(f"{a}: [{e['provision']}](../register/entries/{e['id']}.json) ({e['assessment']['verdict']})" for a,e in by[t])
        out.append(f"| {t} | {cells} | {len(by[t])} entries |")
    else: out.append(f"| {t} | | untested |")
out.append("""
## Untested articles

Article 2 (members including agents), Article 6 (agents) and Article 8 (money kept apart) rest partly on non-state precedents documented in docs/LANDSCAPE.md (Wikipedia agent policy, 1f916 quotas, Aragon dissolution) that are not yet register entries. Adding them as entries is open work.

## Register index

| Entry | Source | Verdict | Lesson |
|---|---|---|---|""")
for e in E:
    out.append(f"| [{e['provision']}](../register/entries/{e['id']}.json) | {e['source']['constitution']}, {e['source']['year']} | {e['assessment']['verdict']} | {e['lesson']} |")
open(os.path.join(root,'docs/EVIDENCE.md'),'w').write('\n'.join(out)+'\n')
print(f"{len(E)} entries valid; evidence map written; untested: {[t for t in titles if not by[t]]}")
